<!DOCTYPE html>
<html lang="en">
<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
wet-boew.github.com/wet-boew/License-eng.txt / wet-boew.github.com/wet-boew/Licence-fra.txt -->
<!-- DataAjaxFragmentStart -->
<li><section><h3><a href="http://www.tpsgc-pwgsc.gc.ca/comm/services-eng.html">PWGSC Services</a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/app-acq/index-eng.html">Buying and Selling</a></h4>
<ul>
<li><a href="https://buyandsell.gc.ca/">Buyandsell.gc.ca</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/ongc-cgsb/index-eng.html">Canadian General Standards Board</a></li>
<li><a href="http://crownassets.pwgsc.gc.ca/mn-eng.cfm">GCSurplus</a></li>
<li><a href="http://www.merx.com/English/nonmember.asp?WCE=Show&amp;TAB=1&amp;PORTAL=MERX&amp;State=1&amp;hcode=0oAbh0Y4HyEmQfk9GqXlQw%3d%3d" rel="external">MERX</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/app-acq/stamgp-lamsmp/amm-mmp-eng.html">Military and Marine Procurement</a></li>
</ul>
</section>

<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/secinfo-eng.html">Security, Corporate and Information Services</a></h4>
<ul>
<li><a href="http://www.gazette.gc.ca/index-eng.html" rel="external">Canada Gazette</a></li>
<li><a href="http://publications.gc.ca/site/eng/home.html" rel="external">Government of Canada Publications</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/ecologisation-greening/index-eng.html">Greening Government</a></li>
<li><a href="http://ssi-iss.tpsgc-pwgsc.gc.ca/index-eng.html">Industrial Security Program</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/isp-ssi/gp-c-eng.html">Shared Services Integration - Clusters</a></li>
</ul>
</section>
</div>

<div class="span-2">
<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/pmnts-eng.html">Payments and Pensions</a></h4>
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/awr-cwa/txt/index-eng.html">Compensation Web Applications</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/recgen/txt/depot-deposit-eng.html">Direct Deposit</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/txt/index-eng.html">Pay and Pension Services for Government Employees</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/recgen/txt/72-eng.html">Public Accounts</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/recgen/txt/index-eng.html">Receiver General for Canada</a></li>
<li><a href="http://pensionetavantages-pensionandbenefits.gc.ca/accueil-home-eng.html">Your Public Service Pension and Benefits</a></li>
</ul>
</section>

<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/trdctn-trnsltn-eng.html">Translation, Interpretation and Other Linguistic Services</a></h4>
<ul>
<li><a href="http://www.noslangues-ourlanguages.gc.ca/index-eng.php" rel="external">Language Portal of Canada</a></li>
<li><a href="http://www.btb.termiumplus.gc.ca/site/termium.php?lang=eng&amp;cont=001">TERMIUM Plus®</a></li>
<li><a href="http://www.btb.gc.ca/btb.php?lang=eng&amp;cont=268">Translation and linguistic services</a></li>
<li><a href="http://www.btb.gc.ca/btb.php?lang=eng&amp;cont=001">Translation Bureau</a></li>
</ul>
</section>
</div>

<div class="span-2">
<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/bns-prprt-eng.html">Property and Buildings</a></h4>
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/pc-cp-eng.html">Construction Projects</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/vdtt-ftrd-eng.html">Featured Properties</a></li>
<li><a href="http://collineduparlement-parliamenthill.gc.ca/index-eng.html">Parliament Hill</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/peri-pilt/index-eng.html">Payments in Lieu of Taxes</a></li>
<li><a href="http://id-reo.tpsgc-pwgsc.gc.ca/public/ffchrdspl.do?lang=eng&amp;page=acclhm">Real Estate for Sale</a></li>
</ul>
</section>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://www.tpsgc-pwgsc.gc.ca/comm/services-eng.html">PWGSC Services - Main page</a></div>
</div></section></li>

<li><section><h3><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/index-eng.html">Information for</a></h3><div class="mb-sm">
<div class="span-2">
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/ntrprss-bsnsss-eng.html">Businesses</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/cndns-eng.html">Canadians</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/gvrnmnt-eng.html">Government</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/medias-media/index-eng.html">Media</a></li>
</ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/index-eng.html">Information for - Main page</a></div>
</div></section></li>

<li><section><h3><a href="http://www.tpsgc-pwgsc.gc.ca/comm/ress-res-eng.html">PWGSC Resources</a></h3><div class="mb-sm">
<div class="span-2">
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/index-az-eng.html">A-Z Index</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/questions-eng.html">Frequently Asked Questions</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/medias-media/index-eng.html">News</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/vedette-features/index-eng.html">Features</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/publications-eng.html">Publications and Reports</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/site-eng.html">Site Map</a></li>
</ul>
</div>
<div class="clear"></div>
<div class="mb-main-link"><a href="http://www.tpsgc-pwgsc.gc.ca/comm/ress-res-eng.html">PWGSC Resources - Main page</a></div>
</div></section></li>
<!-- DataAjaxFragmentEnd -->
</html>
