<!DOCTYPE html>
<html lang="fr">
<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
wet-boew.github.com/wet-boew/License-eng.txt / wet-boew.github.com/wet-boew/Licence-fra.txt -->
<!-- DataAjaxFragmentStart -->
<li><section><h3><a href="http://www.tpsgc-pwgsc.gc.ca/comm/services-fra.html">Services de TPSGC</a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/app-acq/index-fra.html">Achats et ventes</a></h4>
<ul>
<li><a href="https://achatsetventes.gc.ca/">Achatsetventes.gc.ca</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/app-acq/stamgp-lamsmp/amm-mmp-fra.html">Approvisionnement militaire et maritime</a></li>
<li><a href="http://crownassets.pwgsc.gc.ca/mn-fra.cfm">GCSurplus</a></li>
<li><a href="http://www.merx.com/French/nonmember.asp?WCE=Show&amp;TAB=1&amp;PORTAL=MERX&amp;State=1&amp;hcode=0oAbh0Y4HyEmQfk9GqXlQw%3d%3d" rel="external">MERX</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/ongc-cgsb/index-fra.html">Office des normes générales du Canada</a></li>
</ul>
</section>

<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/secinfo-fra.html">Services de sécurité, d'administration et d'information</a></h4>
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/ecologisation-greening/index-fra.html">Écologisation des opérations gouvernementales</a></li>
<li><a href="http://www.gazette.gc.ca/index-fra.html" rel="external">Gazette du Canada</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/isp-ssi/gp-c-fra.html">Intégration des services partagés - Groupes pluricellulaires</a></li>
<li><a href="http://ssi-iss.tpsgc-pwgsc.gc.ca/index-fra.html">Programme de sécurité industrielle</a></li>
<li><a href="http://publications.gc.ca/site/fra/accueil.html" rel="external">Publications du gouvernement du Canada</a></li>
</ul>
</section>
</div>

<div class="span-2">
<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/bns-prprt-fra.html">Biens et immeubles</a></h4>
<ul>
<li><a href="http://id-reo.tpsgc-pwgsc.gc.ca/public/ffchrdspl.do?page=acclhm&amp;lang=fr">Biens immobiliers à vendre</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/vdtt-ftrd-fra.html">Biens immobiliers en vedette</a></li>
<li><a href="http://collineduparlement-parliamenthill.gc.ca/index-fra.html">Colline du Parlement</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/peri-pilt/index-fra.html">Paiements en remplacement d'impôts</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/biens-property/pc-cp-fra.html">Projets de construction</a></li>
</ul>
</section>

<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/trdctn-trnsltn-fra.html">Traduction, interprétation et autres services linguistiques</a></h4>
<ul>
<li><a href="http://www.btb.gc.ca/btb.php?lang=fra&amp;cont=001">Bureau de la traduction</a></li>
<li><a href="http://www.noslangues-ourlanguages.gc.ca/index-fra.php" rel="external">Portail linguistique du Canada</a></li>
<li><a href="http://www.btb.termiumplus.gc.ca/site/termium.php?lang=fra&amp;cont=001">TERMIUM Plus®</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/services/trdctn-trnsltn-fra.html">Traduction et services linguistiques</a></li>
</ul>
</section>
</div>

<div class="span-2">
<section><h4><a href="http://www.tpsgc-pwgsc.gc.ca/services/pmnts-fra.html">Paiements et pensions </a></h4>
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/awr-cwa/txt/index-fra.html">Applications Web de la rémunération</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/recgen/txt/72-fra.html">Comptes publics</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/recgen/txt/depot-deposit-fra.html">Dépôt direct</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/recgen/txt/index-fra.html">Receveur général du Canada</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/txt/index-fra.html">Services de paye et de pension pour les employés du gouvernement du Canada</a></li>
<li><a href="http://pensionetavantages-pensionandbenefits.gc.ca/accueil-home-fra.html">Votre pension et vos avantages sociaux de la fonction publique</a></li>
</ul>
</section>
</div>

<div class="clear"></div>
<div class="mb-main-link"><a href="http://www.tpsgc-pwgsc.gc.ca/comm/services-fra.html">Services de TPSGC - Page principale</a></div>
</div></section></li>

<li><section><h3><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/index-fra.html">Information pour</a></h3><div class="mb-sm">
<div class="span-2">
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/ntrprss-bsnsss-fra.html">Les entreprises</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/cndns-fra.html">Les Canadiens et Canadiennes</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/gvrnmnt-fra.html">Le gouvernement </a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/medias-media/index-fra.html">Les médias</a></li>
</ul>
</div>

<div class="clear"></div>
<div class="mb-main-link"><a href="http://www.tpsgc-pwgsc.gc.ca/comm/info/index-fra.html">Information pour - Page principale</a></div>
</div></section></li>

<li><section><h3><a href="http://www.tpsgc-pwgsc.gc.ca/comm/ress-res-fra.html">Ressources TPSGC</a></h3><div class="mb-sm">
<div class="span-2">
<ul>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/index-az-fra.html">Index A-Z</a></li>				
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/questions-fra.html">Foire aux questions</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/medias-media/index-fra.html">Nouvelles</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/vedette-features/index-fra.html">Dossiers spéciaux</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/publications-fra.html">Publications et rapports</a></li>
<li><a href="http://www.tpsgc-pwgsc.gc.ca/comm/site-fra.html">Plan du site</a></li>
</ul>
</div>

<div class="clear"></div>
<div class="mb-main-link"><a href="http://www.tpsgc-pwgsc.gc.ca/comm/ress-res-fra.html">Ressources TPSGC - Page principale</a></div>
</div></section></li>
<!-- DataAjaxFragmentEnd -->
</html>
