<HTML>
<BODY>
<CENTER>
<B>
<Font face=Arial Size=3>
Fraser River Deep Sea Navigation Channel
</Font>
<BR>
<Font face=Arial Size=2>
Predicted Available Depths for 1 and 2 Lane Channels
<BR>
From Sunday, June 01, 1997 to Sunday, June 08, 1997
</Font>
<BR>
<Font face=Arial Size=2>
Location of Control Points
</Font>
</B>
</CENTER>
<P
>
<CENTER>
<table border=1 cellpadding=1 cellspacing=1 width=75%>
<tr
 bgcolor=#FFFFDD
>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
From
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
To
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
Location
</B>
</Font>
</td>
<td
 rowspan=2
>
<Font face=Arial Size=1>
Survey<BR>Date
</Font>
</td>
</tr>
<tr
 bgcolor=#FFFFDD
>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Time
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Time
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Km
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Name
</Font>
</td>
</tr>
<tr
>
<td
 colspan=7 align=CENTER
>
<Font face=Arial Size=1>
<B>
1 Lane Channel
</B>
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
1Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
6Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
2
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
6Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
6Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Steveston Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
29May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
6Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
6Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
27May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
6Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Steveston Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
29May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
7Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
18.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
27May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
7Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
18.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Steveston Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
29May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
7Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
8Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
27May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
8Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
8Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Steveston Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
29May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
8Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
8Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
27May97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
8Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
9Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Steveston Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
29May97
</Font>
</td>
</tr>
<tr
>
<td
 colspan=7 align=CENTER
>
<Font face=Arial Size=1>
<B>
2 Lane Channel
</B>
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
1Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
9Jun97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
12May97
</Font>
</td>
</tr>
</table>
</CENTER>
