<HTML>
<BODY>
<CENTER>
<B>
<Font face=Arial Size=3>
Fraser River - 2 Lane Navigation Channel
</Font>
<BR>
<Font face=Arial Size=2>
Predicted Available Depths From Wednesday, April 30, 1997 to Wednesday, May 07, 1997
<BR>
Current Soundings at Km 0-35
</Font>
<BR>
<Font face=Arial Size=2>
Location of Control Points
</Font>
</B>
</CENTER>
<P
>
<CENTER>
<table border=1 cellpadding=1 cellspacing=1 width=75%>
<tr
 bgcolor=#FFFFDD
>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
From
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
To
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
Location
</B>
</Font>
</td>
<td
 rowspan=2
>
<Font face=Arial Size=1>
Survey<BR>Date
</Font>
</td>
</tr>
<tr
 bgcolor=#FFFFDD
>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Time
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Time
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Km
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Name
</Font>
</td>
</tr>
<tr
>
<td
 colspan=7 align=CENTER
>
<Font face=Arial Size=1>
<B>
</B>
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
02.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
02.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
12.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
12.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
20.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
20.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
33
</Font>
</td>
<td
>
<Font face=Arial Size=1>
New Westminster
</Font>
</td>
<td
>
<Font face=Arial Size=1>
5Sep96
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
30Apr97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
1May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
1May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
1May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
1May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
12.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
12.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
2May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
3May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
3May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
04.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
3May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
3May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
3May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
3May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
18.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
4May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
18.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
14.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
20.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
5May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
20.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
02.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
02.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
06.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
20.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
6May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
20.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
02.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
02.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
08.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
28
</Font>
</td>
<td
>
<Font face=Arial Size=1>
St. Mungo Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
15Feb97
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
7May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
22.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
8May97
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
0
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Sandheads
</Font>
</td>
<td
>
<Font face=Arial Size=1>
17Apr97
</Font>
</td>
</tr>
</table>
</CENTER>
