<HTML>
<BODY>
<CENTER>
<B>
<Font face=Arial Size=3>
Fraser River - South Arm
</Font>
<BR>
<Font face=Arial Size=2>
Predicted Available Depths From January 19, 2013 to January 26, 2013
<BR>
Current Soundings at Km 0-35
</Font>
<BR>
<Font face=Arial Size=2>
Location of Control Points
</Font>
</B>
</CENTER>
<BR>
<CENTER>
<Font face=Arial Size=2>
<B>
Inner Navigation Channel
</B>
</Font>
</CENTER>
<CENTER>
<table border=1 cellpadding=1 cellspacing=1 width=75%>
<tr
 bgcolor=#FFFFDD
>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
From
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
To
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
Location
</B>
</Font>
</td>
<td
 rowspan=2
>
<Font face=Arial Size=1>
Survey<BR>Date
</Font>
</td>
</tr>
<tr
 bgcolor=#FFFFDD
>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Time
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Time
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Km
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Name
</Font>
</td>
</tr>
<tr
>
<td
 colspan=7 align=CENTER
>
<Font face=Arial Size=1>
<B>
</B>
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
19Jan13
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
27Jan13
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
5
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Steveston Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16Nov12
</Font>
</td>
</tr>
</table>
</CENTER>
