<font face="Arial" color="#000080">

<p><b>Weekly Report - Notes</b></font></p>

<hr noshade size="1">

<p><font face="Arial" size="2">
The available depth information provided in this report is compiled using the most recent hydrographic survey data of the Fraser River obtained by Public Works Canada and predicted
Fraser River water levels provided by the Institute of Ocean Sciences, Fisheries and Oceans Canada.  The discharge is a forecast for each day and identified below the date of each graph.
Variations between the actual and forecasted discharge rate particularly when it exceeds 4,200 cms will cause variations in available depth.  The accuracy of the available depth is limited
to the combined accuracy of the hydrographic surveys and predicted water level tables.  <br>
<br>For additional information contact <a href="mailto:DutchakW@pac.dfo-mpo.gc.ca">Canadian Coast Guard</a>, Superintendent, Waterways Development.
</font></p>

