<HTML>
<BODY>
<BR>
<CENTER>
<Font face=Arial Size=2>
<B>
les chenaux à deux voie
</B>
</Font>
</CENTER>
<CENTER>
<table border=1 cellpadding=1 cellspacing=1 width=75%>
<tr
 bgcolor=#FFFFDD
>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
du
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
Au
</B>
</Font>
</td>
<td
 colspan=2
>
<Font face=Arial Size=1>
<B>
Emplacement
</B>
</Font>
</td>
<td
 rowspan=2
>
<Font face=Arial Size=1>
Survey<BR>Date
</Font>
</td>
</tr>
<tr
 bgcolor=#FFFFDD
>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Heures
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Date
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Heures
</Font>
</td>
<td
>
<Font face=Arial Size=1>
km
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Nom
</Font>
</td>
</tr>
<tr
>
<td
 colspan=7 align=CENTER
>
<Font face=Arial Size=1>
<B>
</B>
</Font>
</td>
</tr>
<tr
 ALIGN=LEFT
>
<td
>
<Font face=Arial Size=1>
19Jan13
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
27Jan13
</Font>
</td>
<td
>
<Font face=Arial Size=1>
00.00
</Font>
</td>
<td
>
<Font face=Arial Size=1>
5
</Font>
</td>
<td
>
<Font face=Arial Size=1>
Steveston Bend
</Font>
</td>
<td
>
<Font face=Arial Size=1>
16Nov12
</Font>
</td>
</tr>
</table>
</CENTER>
