// Generated by CoffeeScript 1.7.0
(function() {
  var preload;

  $(function() {
    var images, path;
    path = '/images/time_series/';
    images = ['SC_0710_ARS_2012.jpg', 'SC_0710_R01_2012.jpg', 'SC_0710_R02_2012.jpg', 'SC_0710_R03_2012.jpg', 'SC_0710_R04_2012.jpg', 'SC_0710_R05_2012.jpg', 'SC_0710_R06_2012.jpg', 'SC_0710_R07_2012.jpg', 'SC_0710_R08_2012.jpg', 'SC_0710_R09_2012.jpg', 'SC_0710_R10_2012.jpg', 'SC_0710_R12_2012.jpg', 'SC_0710_R13_2012.jpg'];
    images = $.map(images, function(n, i) {
      return path + n;
    });
    preload(images);
    return $.each(images, function(i, img) {
      var html;
      html = "<li><a href=\"#tab" + (i + 1) + "\">" + (i + 1) + "</a></li>";
      $('.tabs').append(html);
      html = "<div id=\"tab" + (i + 1) + "\">\n  <section>\n    <div class=\"span-8\"><img src=\"" + img + "\" alt=\"Fraser River\" class=\"margin-bottom-none\" /></div>\n    <div class=\"clear\"></div>\n  </section>\n</div>";
      return $('.tabs-panel').append(html);
    });
  });

  preload = function(arrayOfImages) {
    return $(arrayOfImages).each(function() {
      return $('<img/>')[0].src = this;
    });
  };

}).call(this);
